"""Generate the static tracker from reviewed provider data: python3 scripts/build.py."""
import json
import hashlib
from pathlib import Path
from html import escape as e
from datetime import date
ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'data/rates.json').read_text())
providers = data['providers']
icons = json.loads((ROOT / 'data/provider-icons.json').read_text())
for provider in providers:
    assert provider['id'] in icons, f"Missing provider icon: {provider['id']}"
    assert (ROOT / 'docs' / icons[provider['id']]['path']).is_file()
def rate(n): return '—' if n is None else f'{n:.2f}%'
def rows(category):
    out = []
    for p in sorted((p for p in providers if p['category']==category), key=lambda p: p['boost'] if p['boost'] is not None else p['base'], reverse=True):
        icon = icons[p['id']]['path']
        icon_version = hashlib.sha256((ROOT/'docs'/icon).read_bytes()).hexdigest()[:10]
        top = p['boost'] if p['boost'] is not None else p['base']
        links=' · '.join(f'<a href="{e(s["url"])}" target="_blank" rel="noopener">{e(s["label"])} ↗</a>' for s in p['sources'])
        out.append(f'''<article id="provider-{e(p['id'])}" class="provider-row" data-name="{e(p['name'].lower())}" data-search="{e((p['name']+' '+p['product']+' '+p['kind']).lower())}" data-base="{p['base'] if p['base'] is not None else -1}" data-top="{top}" data-fdic="{e(p['fdic']['status'])}">
<div class="provider"><img class="provider-icon" src="{e(icon)}?v={icon_version}" width="34" height="34" alt="" decoding="async"><div><h3>{e(p['name'])}</h3><p>{e(p['product'])}</p><span class="fdic-badge fdic-{e(p['fdic']['status'])}">{e(p['fdic']['label'])}</span></div></div>
<div class="rate base"><span class="mobile-label">Base APY</span><strong>{rate(p['base'])}</strong><small>{e(p.get('baseLabel', 'Membership required' if p['base'] is None else 'Up to' if p['id']=='kraken' else 'Standard'))}</small></div>
<div class="rate top"><span class="mobile-label">Top APY</span><strong>{rate(top)}</strong><small>{e(p['rateLabel'])}</small></div>
<div class="terms"><p>{e(p['requirements'])}</p><details><summary>Details <span class="details-chevron" aria-hidden="true">›</span></summary><div class="detail-body"><p>{e(p['details'])}</p><p>{e(p['fdic']['summary'])}</p><p><b>Protection:</b> {e(p['protection'])}</p><p class="source-links">{links}</p><p class="checked">Checked {data['checkedAt']} · {'Observed: '+p['observedAt'] if p.get('observedAt') else 'Provider rate date: '+p['effective'] if p['effective'] else 'No effective date published on rate page.'}</p></div></details></div></article>''')
    return '\n'.join(out)
page='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Money — the yield tracker</title><meta name="description" content="Compare cash, savings, and stablecoin yields. Base rates, boosted APYs, requirements, and official sources in one place."><link rel="canonical" href="https://money.ilyusha.xyz/"><meta property="og:title" content="Money — the yield tracker"><meta property="og:description" content="What is your money earning? Compare provider yields and the terms behind them."><meta property="og:type" content="website"><meta property="og:url" content="https://money.ilyusha.xyz/"><meta name="twitter:card" content="summary"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script><script src="analytics.js" defer></script></head>
<body><a class="skip-link" href="#rates">Skip to rates</a><header><a class="brand" href="#top"><span class="brand-mark">m.</span>money<span class="brand-by">/ by ilyusha</span></a><nav aria-label="Main navigation"><a href="#rates">Yield tracker</a><a href="#methodology">How it works</a></nav><a class="personal" href="https://ilyusha.xyz">ilyusha.xyz ↗</a></header>
<main id="top"><section class="hero"><div><p class="eyebrow"><span class="dot"></span> THE YIELD TRACKER / USD</p><h1>Make your <em>money count.</em></h1>LEAD<p class="change-note">CHANGE_NOTE</p></div><aside class="snapshot"><div class="snapshot-count">7<span>providers<br>tracked</span></div><div class="snapshot-date">Checked <time datetime="CHECKED">Oct 3, 2026</time></div><p>Rechecked daily · Rates can change</p></aside></section>
<section id="rates" aria-label="Compare provider yields"><div class="tracker-controls"><div class="toolbar"><div class="filters" role="group" aria-label="Yield category"><button data-category="all" aria-pressed="true" class="active">All providers <span>7</span></button><button data-category="cash" aria-pressed="false">Cash & savings <span>5</span></button><button data-category="crypto" aria-pressed="false">Crypto & stablecoins <span>2</span></button></div><p id="result-count" class="result-count" aria-live="polite">Showing 7 providers</p></div><div class="control-line"><label class="search"><svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><span class="sr-only">Search providers</span><input id="search" type="search" aria-label="Search providers" placeholder="Find a provider…"></label><details class="filter-menu" id="filter-menu"><summary><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="2.5" fill="var(--paper)"/><circle cx="15" cy="17" r="2.5" fill="var(--paper)"/></svg>Filters <b id="filter-count" hidden>0</b></summary><div class="filter-panel"><div class="panel-heading">Refine your results<button id="close-filters" aria-label="Close filters" type="button">×</button></div><label for="coverage">Deposit protection</label><select id="coverage" aria-label="Filter by FDIC coverage"><option value="all">All coverage types</option><option value="bank">FDIC · Bank deposits</option><option value="conditional">FDIC · Conditional</option><option value="mixed">FDIC · Mixed coverage</option><option value="none">Not FDIC insured</option></select><label for="minimum">Minimum top APY</label><select id="minimum" aria-label="Minimum top APY"><option value="0">Any rate</option><option value="3">3% or higher</option><option value="4">4% or higher</option><option value="5">5% or higher</option></select><p>Filters apply as you choose.</p></div></details><label class="sort-control"><span class="sr-only">Sort providers</span><select id="sort" aria-label="Sort providers"><option value="top">Top APY: High → low</option><option value="top-asc">Top APY: Low → high</option><option value="base">Base APY: High → low</option><option value="base-asc">Base APY: Low → high</option><option value="name">Name: A → Z</option></select></label></div><div class="active-filter-line" id="active-filter-line" hidden><span id="active-filters"></span><button id="reset" type="button">Clear all</button></div></div><p class="category-hint">Top rates may require qualifying activity, fees, or limited balances. <a href="#methodology">How we compare ↗</a></p>
<section class="rate-group" data-group="cash"><div class="group-heading"><div><span class="eyebrow">01 / CASH & SAVINGS</span><h2>Cash & savings<span>.</span></h2></div><p>Bank accounts, fintech savings & cash management</p></div><div class="column-head"><span>PROVIDER / ACCOUNT</span><button type="button" data-sort="base">BASE APY ↕</button><button type="button" data-sort="top">TOP APY ↓</button><span>WHAT TO KNOW</span></div><div class="rows">CASH_ROWS</div></section>
<section id="crypto-rates" class="rate-group crypto-group" data-group="crypto"><div class="group-heading"><div><span class="eyebrow">02 / CRYPTO & STABLECOINS</span><h2>Crypto & stablecoins<span>.</span></h2></div><p>Digital assets · USDC rewards & onchain lending</p></div><div class="crypto-note"><span aria-hidden="true">↳</span> These are crypto rewards, not insured savings. Stablecoins can lose their peg. Custody and smart-contract risks vary by product.</div><div class="column-head"><span>PROVIDER / ASSET</span><button type="button" data-sort="base">BASE APY ↕</button><button type="button" data-sort="top">TOP APY ↓</button><span>WHAT TO KNOW</span></div><div class="rows">CRYPTO_ROWS</div></section>
<p id="empty" hidden>No matching providers. Try a lower minimum APY, another coverage type, or reset the filters above.</p><noscript><p class="noscript">All rates are shown below. Enable JavaScript to search, filter, and sort.</p></noscript></section>
<section class="methodology" id="methodology"><div><p class="eyebrow">BEHIND THE NUMBERS</p><h2>Read the rate.<br><em>Then the terms.</em></h2></div><div class="method-grid"><div><h3>Base vs. top</h3><p>Coverage is curated across US providers; CDs, targeted offers, and cash signup bonuses are excluded. Base is the standard rate for the stated tier. Top is the highest verified public offer for the listed account, including referral boosts, promotions, and qualifying tiers. Caps, fees, and eligibility appear alongside it; boosts are combined only where the provider permits.</p></div><div><h3>Checked, not streamed</h3><p>This is a reviewed snapshot of official provider pages, checked CHECKED. Rates are rechecked daily against those pages, not streamed live. Every listing links to its sources and provider date when available.</p></div><div><h3>APY isn’t take-home yield</h3><p>APY includes compounding. Membership costs, taxes, balance caps, and temporary boosts affect what you earn. Rates are variable; a three-month promotion is not a one-year return.</p></div><div><h3>What FDIC coverage means</h3><p>FDIC coverage is generally $250,000 per depositor, per insured bank, per ownership category. Deposits held directly or through different apps at the same bank count together. Pass-through coverage requires program conditions to be met. It covers insured bank failure, not a fintech platform’s failure or crypto losses. <a href="https://www.fdic.gov/resources/deposit-insurance/understanding-deposit-insurance" target="_blank" rel="noopener">FDIC coverage rules ↗</a></p></div></div></section>
</main><a class="back-top" href="#rates" aria-label="Back to filters">↑ Filters</a><footer><span>Money / An independent tracker by <a href="https://ilyusha.xyz">Ilyusha ↗</a></span><a href="mailto:dev@ilyusha.xyz?subject=Money%20tracker%20correction">Suggest a provider or correction ↗</a></footer></body></html>'''
page=page.replace('7<span>providers',f'{len(providers)}<span>providers').replace('All providers <span>7</span>',f'All providers <span>{len(providers)}</span>').replace('Cash & savings <span>5</span>',f'Cash & savings <span>{sum(p["category"]=="cash" for p in providers)}</span>').replace('Crypto & stablecoins <span>2</span>',f'Crypto & stablecoins <span>{sum(p["category"]=="crypto" for p in providers)}</span>').replace('Showing 7 providers',f'Showing {len(providers)} providers').replace('Oct 3, 2026',date.fromisoformat(data['checkedAt']).strftime('%b %-d, %Y'))
def offer_rate(p):
    return p['boost'] if p['boost'] is not None else p['base']
ranked = sorted(providers, key=lambda p: offer_rate(p) if offer_rate(p) is not None else -1, reverse=True)[:6]
top = offer_rate(ranked[0]) or 1
bars = []
for p in ranked:
    value = offer_rate(p) or 0
    width = max(8, round(value / top * 100))
    bars.append(f'<a class="bar-row" href="#provider-{e(p["id"])}"><b>{e(p["name"])}</b><span class="bar"><i style="width:{width}%"></i></span><strong>{rate(value)}</strong><small>{e(p["requirements"])}</small></a>')
lead = '<figure class="share-chart"><figcaption>Top verified APY</figcaption>' + ''.join(bars) + '</figure>'
note = data.get('changeNote') or 'Top verified offers on this snapshot.'
names = ', '.join(p['name'] for p in ranked)
page=page.replace('LEAD', lead).replace('CHANGE_NOTE', e(note))
page=page.replace('CASH_ROWS',rows('cash')).replace('CRYPTO_ROWS',rows('crypto')).replace('CHECKED',data['checkedAt'])
page=page.replace('Compare provider yields and the terms behind them.', f'Top verified offers: {names}. Compare yields and the terms behind them.')
for asset in ('styles.css', 'app.js', 'analytics.js'):
    version = hashlib.sha256((ROOT/'docs'/asset).read_bytes()).hexdigest()[:10]
    page = page.replace(f'"{asset}"', f'"{asset}?v={version}"')
(ROOT/'docs/index.html').write_text(page)
print(f'Built tracker with {len(providers)} providers.')
